### ISSUE TITLE
undefined method when importing from friendfeed

### ISSUE THREAD

**Issue by grimborg** [dominiek/kakuteru#1]
Hi,
I'm getting this error when executing ./script/runner Post.fetch_from_friendfeed
I'm using rails 2.1.1 (app didn't start with the latest version). My zementa api key is in the environtment.rb (ZEMENTA_API_KEY)
I tried using both http://friendfeed.com/myuser and http://friendfeed.com?format=atom as the url, to no avail.

/var/lib/gems/1.8/gems/rails-2.1.1/lib/commands/runner.rb:47: undefined method `name' for "\n\n":REXML::Text (NoMethodError)
    from /usr/lib/ruby/1.8/rexml/parent.rb:40:in`each'
    from /usr/lib/ruby/1.8/rexml/parent.rb:40:in `each'
    from /home/oscar/kaku/kakuteru/lib/friendfeed.rb:17:in`fetch'
    from /home/oscar/kaku/kakuteru/app/models/post.rb:32:in `fetch_from_friendfeed'
    from (eval):1
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`eval'
    from /var/lib/gems/1.8/gems/rails-2.1.1/lib/commands/runner.rb:47
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in`require'
    from ./script/runner:3

Ideas?

Thanks!

**Comment by grimborg** [comment]
I meant http://friendfeed.com/myuser?format=atom
